### ISSUE TITLE
Typo in code for chapter 4 exercises

### ISSUE THREAD

**Issue by DarrenKirby** [mikexcohen/Statistics_book#4]
Hi Mike. I think I have found a typo in the code for Exercise 1 in chapter 4, found in [this file](https://github.com/mikexcohen/Statistics_book/blob/main/python/stats_ch04_descriptives.ipynb). In the section which begins with the comment 'Create a family of Gaussians'  there is this:

```
for i in range(N):
  a = 1 / (sigmas[i]*np.sqrt(2*np.pi))
  eTerm = -x**2 / (2*sigmas[i]**2)
  G[i,:] = np.exp( eTerm )
```

which I think should be:

```
for i in range(N):
  a = 1 / (sigmas[i]*np.sqrt(2*np.pi))
  eTerm = -x**2 / (2*sigmas[i]**2)
  G[i,:] = a * np.exp( eTerm )
```

The code as written populates a matrix which generates this plot:
<img width="933" alt="Screenshot 2024-09-03 at 11 37 15 AM" src="https://github.com/user-attachments/assets/c56bfd60-ca58-415e-85e2-704b4315165e">

...when it should generate this plot:

<img width="789" alt="Screenshot 2024-09-03 at 11 37 56 AM" src="https://github.com/user-attachments/assets/ee3136b3-f705-40a2-8010-552bf7b07e03">

**Comment by DarrenKirby** [comment]
Oh, sorry. I just worked through exercise 2 and see it was intentional. Apologies for the noise...

**Comment by mikexcohen** [comment]
Hi Darren. Actually, your first message was correct: it was a bug in the code :P   In fact, that variable `a` isn't used in the for-loop.

I had a quick look at the video walkthrough of this exercise, and I think what happened is that I changed the code while recording the video and then forgot to change it back before pushing to git. I fixed it now; thanks for taking the time to report that!
